import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { pressStart2P } from "@/ui/fonts"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${pressStart2P.className} ${geistSans.variable} ${geistMono.variable} antialiased crtTextShadowDf tracking-wider bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-[#3c3c3c]  to-[#0e0e0e] text-white`}>
        {children}
        <div
          className="pointer-events-none overflow-hidden fixed inset-0 w-full h-full opacity-60 bg-[linear-gradient(rgba(18,16,16,0),rgba(0,0,0,0.25)),linear-gradient(90deg,rgba(255,0,0,0.06),rgba(0,255,0,0.02),rgba(0,0,255,0.06))] bg-[length:100%_3px,2px_100%]"></div>
        <div className="w-full h-[100px] z-[8] bg-gradient-to-t from-transparent via-[rgba(255,255,255,0.2)] to-[rgba(0,0,0,0.1)] opacity-10 absolute bottom-[100%] animate-scanline pointer-events-none"></div>
      </body>
    </html>
  )
}
